# Generated by Django 5.2.11 on 2026-02-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habituseful",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("everyday", "Каждый день"),
                    ("every two day", "Каждые два дня"),
                    ("every three day", "Каждые три дня"),
                    ("every fhour day", "Каждые четыре дня"),
                    ("every five day", "Каждые пять дней"),
                    ("every six day", "Каждые шесть дней"),
                    ("every week", "Каждую неделю"),
                ],
                default="everyday",
                help_text="Раз во сколько дней",
            ),
        ),
    ]
