# Generated by Django 5.2.11 on 2026-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habituseful_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="habituseful",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
