# Generated by Django 5.2.11 on 2026-02-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habituseful_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habituseful",
            name="periodicity",
        ),
    ]
