# Generated by Django 5.2.11 on 2026-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habituseful_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="habituseful",
            name="periodicity",
            field=models.IntegerField(
                choices=[
                    (1, "Каждый день"),
                    (2, "Каждые два дня"),
                    (3, "Каждые три дня"),
                    (4, "Каждые четыре дня"),
                    (5, "Каждые пять дней"),
                    (6, "Каждые шесть дней"),
                    (7, "Каждую неделю"),
                ],
                default=1,
                help_text="Раз во сколько дней",
            ),
        ),
    ]
