# Generated by Django 5.2.11 on 2026-02-23 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habituseful_periodicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habituseful",
            old_name="time_сheck",
            new_name="time_check",
        ),
        migrations.AddField(
            model_name="habituseful",
            name="created_at",
            field=models.DateField(default=datetime.date(2026, 2, 23)),
        ),
        migrations.AlterField(
            model_name="habituseful",
            name="time_of_day",
            field=models.TimeField(
                default=datetime.time(21, 30), help_text="Время выполнения привычки"
            ),
        ),
    ]
