# Generated by Django 5.2.11 on 2026-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_rename_time_сheck_habituseful_time_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habituseful",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
