# Generated by Django 5.2.11 on 2026-02-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_alter_habituseful_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitnice",
            name="action",
        ),
        migrations.RemoveField(
            model_name="habituseful",
            name="action",
        ),
    ]
