# Generated by Django 5.2.11 on 2026-02-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_remove_habitnice_action_remove_habituseful_action"),
        ("locareward", "0002_likeaction_needaction_delete_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitnice",
            name="need_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_habits",
                to="locareward.needaction",
                verbose_name="Нужное действие",
            ),
        ),
        migrations.AddField(
            model_name="habituseful",
            name="like_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_habits",
                to="locareward.likeaction",
                verbose_name="Любимое действие",
            ),
        ),
    ]
